const prompts = {
    dev: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'dev'. Each entry should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, ensuring accuracy and no alterations. For 'proposition', create a counterpoint or alternative perspective, designed to stimulate critical thinking. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure all excerpts are exact, direct quotes from the provided text.`,
    sum: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'sum'. Each entry should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote only the verbose parts of the text. For 'proposition', craft a more concise version of the sentence, aiming to cut down on wordiness while preserving the original intent and meaning. This approach should focus on eliminating unnecessary details and simplifying complex phrasing to improve overall readability. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. The 'proposition' must ensure clarity and brevity, making the sentence easier to understand.`,
    ela: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'ela'. Each entry should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that are brief or lacking in detail. For 'proposition', provide a more developed and comprehensive version of the sentence, adding depth and context to enrich the reader's understanding. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10.  Ensure the 'proposition' offers a meaningful expansion on the original sentence.`,
    chi: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'chi'. Each entry should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that are complex or difficult to understand. For 'proposition', provide a simplified and accessible version of the sentence, using straightforward language and concepts that can be easily understood by children or laypeople. This simplification should make the content more approachable. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' makes the original sentence easy to understand without losing its essential meaning.`,
    sen: `You're an assistant tasked with writing a text analysis in the form of a JSON object named 'sen'. Each entry should include 'excerpt', 'proposition', and 'importance'. For 'excerpt', directly quote the text, focusing on sentences that could be considered sensitive or potentially offensive. For 'proposition', offer a rephrased version of the sentence that maintains the original intent but in a more considerate or sensitive manner, aiming to minimize the risk of offending or hurting the feelings of any group or individual. For 'importance', assign a numerical value reflecting the proposition's significance. This numerical value should range from 1 to 10. Ensure the 'proposition' thoughtfully addresses the sensitivities involved without diluting the original message.`

};

module.exports = { prompts };
